OF_MAINTAINER_PATCH_VERSION := 1
OF_MAINTAINER := Shangshanruo
OF_MAINTAINER_AVATAR := /dev/null

OF_SCREEN_H := 1650

OF_STATUS_H := 65

OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48

OF_CLOCK_POS := 1

OF_ALLOW_DISABLE_NAVBAR := 0

OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 0
OF_NO_RELOAD_MAGISKBOOT := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_NO_MIUI_PATCH_WARNING := 1

OF_SKIP_METADATA_DECRYPTION_WAIT := 0

OF_DONT_PATCH_ENCRYPTED_DEVICE := 1

OF_KEEP_DM_VERITY := 1

OF_USE_MAGISKBOOT_COMPRESSED_WEBP := 0

OF_ENABLE_LPTOOLS := 1
OF_QUICK_BACKUP_LIST := /boot;/data;

FOX_ENABLE_APP_MANAGER=1
FOX_ENABLE_KERNELSU_SUPPORT=1
FOX_USE_BASH_SHELL=1