OF_MAINTAINER_PATCH_VERSION := 1
OF_MAINTAINER := Shangshanruo
OF_MAINTAINER_AVATAR := /dev/null

OF_SCREEN_H := 2472

OF_STATUS_H := 65

OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48

OF_CLOCK_POS := 1

OF_ALLOW_DISABLE_NAVBAR := 0

OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 0
OF_NO_RELOAD_MAGISKBOOT := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_NO_MIUI_PATCH_WARNING := 1

OF_DONT_PATCH_ENCRYPTED_DEVICE := 1

OF_KEEP_DM_VERITY := 1

OF_USE_MAGISKBOOT_COMPRESSED_WEBP := 0

OF_ENABLE_LPTOOLS := 1
OF_QUICK_BACKUP_LIST := /boot;/data;

FOX_ENABLE_APP_MANAGER=1
FOX_USE_BASH_SHELL=1

OF_FBE_METADATA_MOUNT_IGNORE=1
OF_SKIP_ORANGEFOX_PROCESS=1
OF_PATCH_AVB20=1
FOX_USE_TAR_BINARY=1
FOX_USE_SED_BINARY=1
FOX_USE_XZ_UTILS=1
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=0
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
OF_DISABLE_MIUI_OTA_BY_DEFAULT=0
OF_RUN_POST_FORMAT_PROCESS=1
OF_FLASHLIGHT_ENABLE=1
OF_FL_PATH1 := "/sys/class/leds/flashlight/brightness"
OF_USE_NEW_MAGISKBOOT=1